### ISSUE TITLE
Erro ao atualizar o repositório

### ISSUE THREAD

**Issue by codder404** [LeonardoCesca/js-docs#23]
Quando tento alinhar o código com a master, estou a receber o seguinte erro:

![Captura de ecrã de 2020-02-26 21-19-19](https://user-images.githubusercontent.com/39916301/75385912-026ff900-58e1-11ea-8dd0-f55e2d4ab505.png)
![Captura de ecrã de 2020-02-26 21-19-31](https://user-images.githubusercontent.com/39916301/75385958-1582c900-58e1-11ea-9ce1-1bd49356733c.png)

O que estou fazendo de errado?

**Comment by viniciusgusmao** [comment]
Fala codder404. 

Você configurou a url do upstream como sendo https://github.com/ORIGINAL_OWNER/ORIGINAL_REPOSITORY.git. Note que o ORIGINAL_OWNER e o ORIGINAL_REPOSITORY precisa ser modificado colocando os nomes reais do criador do repositório e nome do repositório, respectivamente.

Vai ficar assim: https://github.com/LeonardoCesca/js-docs.git
Ou seja, o ORIGINAL_OWNER é o LeonardoCesca e o ORIGINAL_REPOSITORY é o js-docs.

Para alterar, use o comando no diretório do projeto: 
git remote set-url upstream https://github.com/LeonardoCesca/js-docs.git

**Comment by codder404** [comment]
Valeu viniciusgusmao
