### ISSUE TITLE
Altura dinâmica do iframe baseada no conteúdo

### ISSUE THREAD

**Issue by viniciusgusmao** [LeonardoCesca/js-docs#25]
O que acham de colocar uma altura dinâmica do iframe do jsfiddle de acordo com a quantidade de conteúdo existente nele ? Penso que a barra de rolagem prejudica a leitura dos códigos js de exemplo.

Podíamos criar uma propriedade de altura que seria passada para o componente Iframes via props ou pensar em alguma outra forma também.

**Comment by brunormferreira** [comment]
Olá @viniciusgusmao,

Acho uma boa ideia, inclusive a solução, porém, será que não quebraria o padrão das páginas, pelo fato de cada altura dos frames forem diferente uma da outra?

**Comment by viniciusgusmao** [comment]
Realmente, com essa alteração para altura dinâmica perderíamos este padrão existente das alturas dos iframes nas páginas. Porém ganharíamos uma melhor legibilidade do conteúdo dos iframes, uma vez que não precisaríamos ficar usando a barra de rolagem o tempo todo para entender algum código mais extenso do javascript.

**Comment by brunormferreira** [comment]
Eu concordo com o que você citou, inclusive no começo do projeto eu e o @LeonardoCesca estávamos com esta idéia, porém, se tivesse muito código dentro do iframe, ele ficaria enorme, tomando um grande espaço da página e perdendo a usabilidade, será que ainda permaneceria usual? Acho que o @oniag que é UX, poderia nos ajudar nisto.

**Comment by oniag** [comment]
@brunormferreira Olá, vi só agora a notificação.
Se você parar para pensar, quem acessa o sistema pelo desktop, o jsfiddle com uma altura dinâmica seria ótimo, mas a partir do momento que o nosso usuário acessa pelo celular ou um dispositivo com uma resolução menor irá atrapalhar um pouco, pois geraria uma rolagem muito maior que o normal, e cá entre nós, ninguém gosta de rolar a página por muito tempo mesmo sendo um conteúdo bacana. 
Uma sugestão que **eu** acho válida é fazer para resoluções maiores o iframe dinamicamente e celulares deixar com a barra de rolagem.
Abraço e até mais.

**Comment by brunormferreira** [comment]
@oniag Sem stress bro. Muito obrigado pelo comentário, concordo plenamente com você.
O que você acha @LeonardoCesca ?

 Acho que o @viniciusgusmao consegue implementar isto para nós então?

**Comment by LeonardoCesca** [comment]
@brunormferreira concordo com o @oniag, em resoluções menores o tamanho do iframe vai ficar desproporcional e acabará gerando um scroll muito grande para o usuário. 

@viniciusgusmao, de fato, sua ideia na teoria é muito boa e talvez fique legal no desktop apesar de não seguir um padrão de altura de iframe em todo o site. Além disso, poderá ocorrer de páginas ficarem com iframes grandes e outras com iframes pequenos (pegando como referencia altura). Mas a unica forma de chegarmos a conclusões mais sérias é realmente testando.

**Comment by viniciusgusmao** [comment]
Entendi. Vou seguir a dica do @oniag e implementar a altura do iframe de acordo com o dispositivo que estiver acessando. 
Vou começar a trabalhar nisso e quando acabar mando a PR para análise.

**Comment by brunormferreira** [comment]
Bom dia! Irei dar close na issue e qualquer eventualidade ou mudança nos reabrimos!

Att,
