### ISSUE TITLE
Dúvida

### ISSUE THREAD

**Issue by codder404** [LeonardoCesca/js-docs#26]
Boa tarde pessoal, eu gostaria de saber, para contribuir só devo me basear no Kanban ou qualquer feature JavaScript serve?

**Comment by LeonardoCesca** [comment]
Boa tarde @codder404,

É possível contribuir com features novas do JavaScript. Porém, todos os PR'S passam por aprovação.

Fique à vontade

**Comment by codder404** [comment]
Boa tarde @LeonardoCesca 
Obrigado
